resources:
- repo: self
queue:
  name: Hosted VS2017
  demands: azureps


variables:
  StorageAccount: 'dddmelbournedeployments'
  StorageContainer: 'ddd-functions'
steps:
- task: Npm@1
  inputs:
    workingDir: DDD.Functions
    verbose: false

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '$(Parameters.RestoreBuildProjects)'

- task: DotNetCoreCLI@2
  inputs:
    projects: '$(Parameters.RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '$(Parameters.TestProjects)'
    arguments: '--configuration $(BuildConfiguration) --no-build'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'DDD.Functions\DDD.Functions.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)\$(Build.BuildNumber)'
    modifyOutputPath: false

- task: AzureFileCopy@1
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)\$(Build.BuildNumber)\$(Build.BuildNumber).zip'
    azureSubscription: 'Microsoft Azure Sponsorship (dd079971-2023-4b56-be3a-85a346d51344)'
    Destination: AzureBlob
    storage: '$(StorageAccount)'
    ContainerName: '$(StorageContainer)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: infrastructure
    ArtifactName: infrastructure
    publishLocation: Container
